<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0;net11.0</TargetFrameworks>
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DryIoc.Microsoft.DependencyInjection\DryIoc.Microsoft.DependencyInjection.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-rc.1.26425.128" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-rc.1.26425.128" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Specification.Tests" Version="11.0.0-rc.1.26425.128" />
    </ItemGroup>

</Project>
