// <auto-generated/>
// Generated from CompileTimeDI/Container.Generated.tt via dotnet-t4.
// Registrations source: IWeatherService → WeatherService (no constructor dependencies).
// To regenerate: dotnet t4 -P="<DryIoc bin dir>" -r=DryIoc.dll -o=CompileTimeDI/Container.Generated.cs CompileTimeDI/Container.Generated.tt
using System;
using System.Collections.Generic;
using DryIoc.ImTools;

namespace DryIoc
{
    ///<summary>Compile-time container: resolves <see cref="IWeatherService"/> without reflection.</summary>
    public sealed class CompileTimeContainer : ICompileTimeContainer
    {
        ///<summary>Singleton instance.</summary>
        public static readonly CompileTimeContainer Instance = new CompileTimeContainer();

        private readonly ValueTuple<Type, object>[] _roots =
        {
            (typeof(IWeatherService), null),
        };

        /// <inheritdoc/>
        public ValueTuple<Type, object>[] GetResolutionRoots() => _roots;

        /// <inheritdoc/>
        public bool TryResolve(out object service, IResolverContext r, Type serviceType)
        {
            if (serviceType == typeof(IWeatherService))
            {
                service = Get_IWeatherService_0(r);
                return true;
            }
            service = null;
            return false;
        }

        /// <inheritdoc/>
        public bool TryResolve(out object service, IResolverContext r,
            Type serviceType, object serviceKey, Type requiredServiceType, Request preRequestParent, object[] args)
        {
            service = null;
            return false;
        }

        /// <inheritdoc/>
        public IEnumerable<ResolveManyResult> ResolveMany(IResolverContext _, Type serviceType)
        {
            if (serviceType == typeof(IWeatherService))
                yield return ResolveManyResult.Of(r => Get_IWeatherService_0(r));
        }

        internal static IWeatherService Get_IWeatherService_0(IResolverContext r) =>
            new WeatherService();
    }
}
